title = "ChaosBlog"
baseURL = "https://blog.networkchallenge.de/"
languageCode = "de-de"
paginate = 10
theme = "startbootstrap-clean-blog"
copyright = "Copyright © ChaosBlog 2018"
disqusShortname = "thechaosblog"

[permalinks]
post = "/post/:filename"

[params]
Author = "Andreas Groll"
description = "Ein Blog über alles aus dem Leben mit den Schwerpunkten DevOps, Fotos, Reisen, Technik und Gadgets."
dateForm = "2. Jan 2006"
dateFormDateTime = "2006-01-02"
imgurl = "https://imgs.networkchallenge.de"

[[params.social]]
  title = "google-plus"
  url = "https://plus.google.com/+AndreasGroll"
[[params.social]]
  title = "github"
  url = "https://github.com/adulescentulus"
[[params.social]]
  title = "instagram"
  url = "https://www.instagram.com/holygrolli/"

[[menu.main]]
  name = "Weltreise"
  url = "/rtw"
  weight = -210
[[menu.main]]
  name = "Über"
  url = "/about"
  weight = -200
[[menu.main]]
  name = "Archiv"
  url = "/post/"
  weight = -180

[[params.authoren]]
key = "grolland"
name = "Andreas Groll"
[[params.authoren]]
key = "katrin"
name = "Katrin Seifert"